### ISSUE TITLE
Change the way retries works

### ISSUE THREAD

**Issue by odolbeau** [odolbeau/rabbit-mq-admin-toolkit#29]
Currently when you specify the property `retries` for a given queue, it will create 1 retry queue per entries in the array.
For example, if you have:
```
queues:
  my_queue:
    durable: true
    retries: [30, 100, 100]
    bindings: my_exchange:my_routing_key
```
You will end with the following queues:
* my_queue
* my_queue_retry_1
* my_queue_retry_2
* my_queue_retry_3

Both queues `my_queue_retry_2` & `my_queue_retry_3` will have the same ttl.
If you want to have several retries with all the same values, that's a lot of useless queues.

That's why I propose the following change:
* all retry queues will be suffixed by the ttl used instead of the retry attempt number (in our case: `my_queue_retry_30`, `my_queue_retry_100`). *This is a BC break* but this will reduce the number of queues created in some use cases.
* we still have only one `retry` exchange
* we still have the same amount of bindings (in our case: `retry:my_queue_retry_1 => my_queue_retry_30`, `retry:my_queue_retry_2 => my_queue_retry_100`, `retry:my_queue_retry_3 => my_queue_retry_100`)

WDYT @stof @Shine-neko @antoox @iamluc  @joelwurtz @Domisys  ?

Please give me your opinion as this BC break could lead to a lot of manual operations during migrations (delete old bindings).

**Comment by joelwurtz** [comment]
Why not using a single queue and set the ttl per message (as see here : https://www.rabbitmq.com/ttl.html) ? It may be better than having to create specific queues for each ttl ?

In fact you may not need at all the retry queue, and only a dl queue by using this method.

**Comment by odolbeau** [comment]
Unfortunately, if you use different ttl, you won't have the expected behaviour:

> When setting per-message TTL expired messages can queue up behind non-expired ones until the latter are consumed or expired. 

Which means, if you publish a first message with a ttl of 10 seconds and a second one with a ttl of 5 seconds, the second one will expire after 10 seconds.

**Comment by joelwurtz** [comment]
> Which means, if you public a first message with a ttl of 10 seconds and a second one with a ttl of 5 seconds, the second one will expire after 10 seconds.

Seems strange, as in this case the functionnality seems totally useless. Did you try to confirm the behavior ? Will do it if not, i just find the documentation not really clear.

**Comment by odolbeau** [comment]
It makes sense given the RMQ is FIFO but you're right, I don't know which use case it covers. :/
I think I confirmed the behaviour before using delayed queues, probably 2 or 3 years ago.

**Comment by iamluc** [comment]
I don't use this feature so I could say something stupid :-)

But this could be incompatible with the option `retry_routing_key_pattern` (See http://blog.eleven-labs.com/en/rabbitmq-publish-consume-retry-messages/).

For `retry_routing_key_pattern: 'send_astronaut_to_space_retry_%%attempt%%'`, what should be the replacement for `%attempt% ` ?

**Comment by odolbeau** [comment]
The queue name will change but the routing key will stay the same.
It means you won't have to do any change in your application (either on the publication side or on the consumer side). :)

**Comment by joelwurtz** [comment]
it may need however a major version, as it will be a bc break for existing environment, doesn't it ?

**Comment by odolbeau** [comment]
Yes, of course. :)
The goal is also to warn as many people as possible regarding this change which can lead to duplicate messages if the bump to the next major version is not made carefully.

**Comment by rpierlot** [comment]
sounds good to me :)
