### ISSUE TITLE
Exchange name

### ISSUE THREAD

**Issue by loicdev** [odolbeau/rabbit-mq-admin-toolkit#39]
Hello, just a question : 
Can we rename the retry and dl exchange in the yaml options ?

**Comment by odolbeau** [comment]
Hi.
Right now it's not possible both exchange names are hardcoded (see [here](https://github.com/odolbeau/rabbit-mq-admin-toolkit/blob/master/src/Bab/RabbitMq/VhostManager.php#L382-L405)).
Feel free to contribute. :)

**Comment by loicdev** [comment]
Thanks for your answer ;)
