### ISSUE TITLE
Blocks installation of swarrot 4.x

### ISSUE THREAD

**Issue by kissifrot** [odolbeau/rabbit-mq-admin-toolkit#51]
Hello,

v5.0 version of the package prevents installation of `swarrot/swarrot ^4.0` , maybe you could update version requirements to something like `swarrot/swarrot ^3.0|^4.0` ?

**Comment by odolbeau** [comment]
Hi @kissifrot!
Of course it's possible, I didn't update this library after releasing latest version of swarrot.

Feel free to make a PR if you want. :)

**Comment by odolbeau** [comment]
You can even require `swarrot/swarrot ^4.0` only, it will be even better. :)

**Comment by kissifrot** [comment]
Done in PR #52 ;)

**Comment by odolbeau** [comment]
Fixed by #52
